language: node_js
node_js:
  - '6.2'
install:
  - npm install
deploy:
  provider: heroku
  api_key:
    secure: LaGtyUyGsXhTDpU1q/HxscsMH1ZOv9dggKRnielN6ItQdtZehBm9Knko09glN3j4EkJuZWd9Cce6s0UQ7MVA1NJ/TFEKQi3Q6mru9vrjFaA8NLTQd6c+k4QT6yJ/V6ionsN5R62qDIL41nR5hsOfiQ38Jgfhv9TEa2fhnsp3f3h+xF5XsuVzD774zJnYeKpLF/f1uGIELtqShIiQHD/nt7IAmYkxqXCQ33h4p7q9RF3Brb5bS0T1pX/h9lwzTCNv+hYYmmZHwAtegv3IkU3BPWw/3BuIJ+TSnnKnJ+/9I58hTZ1quO79yDF5k9pXlSREP+sW42R8QEBLfKbUxrpPAPgM8Pa1Ep9AeGQkC657l7MeGWXqmrEZvW1TWluheuoXgScLGMpSqcT1Vb1re8fXIZBHill/iZzKTgZA3lIiosidS4Gdd1CEyD3rZnHzqQlHUBclTWt1bH+HtM5wX5FssCzadBgkzq7quzIpyEGvURmQOtioNwkZNOiPCqnV8GnMs+uLA/57MpYL+FStKOXH4T82ofHUIqUgiLWqGf2FzQIJmkF3lBfDhlQm9N2LeIkn6cwkfptUHFkY2q/orn/Jd5blRLc/P+t5fZ8sUzYweEbU6DZyCXYYRaO9ESBrzQYSdgkPYUVO0Mtt9TfwHMvjX4/kwNbxwpn2GqR6Wq/eIVY=
  app: fast-curious
  on:
    repo: ripleyaffect/2-fast-2-curious